In [1]:
#Perform the following actions in your dataset:
#1. Read the column description and ensure you understand each attribute well


#Because the department wants to build a model that will help them identify the potential customers who have higher probability of purchasing the loan,
#so that the target should be ["Personal Loan"], and the others should be attribute

#numbeical value: ["Age", "Experience","Income","Family","CCAvg","Mortgage"]

#categorical value: ["ZIPCode","Education","Securities Account", "CD Account", "Online", "CreditCard"]

#target = ["Personal Loan"]


In [33]:
#2. Study the data distribution in each attribute, share your findings. (5 points)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

bank_data = pd.read_csv("Bank_Personal_Loan_Modelling.csv")
bank_data



ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  \
0        1   25           1      49     91107       4   1.60          1   
1        2   45          19      34     90089       3   1.50          1   
2        3   39          15      11     94720       1   1.00          1   
3        4   35           9     100     94112       1   2.70          2   
4        5   35           8      45     91330       4   1.00          2   
5        6   37          13      29     92121       4   0.40          2   
6        7   53          27      72     91711       2   1.50          2   
7        8   50          24      22     93943       1   0.30          3   
8        9   35          10      81     90089       3   0.60          2   
9       10   34           9     180     93023       1   8.90          3   
10      11   65          39     105     94710       4   2.40          3   
11      12   29           5      45     90277       3   0.10          2   
12      13   48          23     114     93106       2   3.80          3   
13      14   59          32      40     94920       4   2.50          2   
14      15   67          41     112     91741       1   2.00          1   
15      16   60          30      22     95054       1   1.50          3   
16      17   38          14     130     95010       4   4.70          3   
17      18   42          18      81     94305       4   2.40          1   
18      19   46          21     193     91604       2   8.10          3   
19      20   55          28      21     94720       1   0.50          2   
20      21   56          31      25     94015       4   0.90          2   
21      22   57          27      63     90095       3   2.00          3   
22      23   29           5      62     90277       1   1.20          1   
23      24   44          18      43     91320       2   0.70          1   
24      25   36          11     152     95521       2   3.90          1   
25      26   43          19      29     94305       3   0.50          1   
26      27   40          16      83     95064       4   0.20          3   
27      28   46          20     158     90064       1   2.40          1   
28      29   56          30      48     94539       1   2.20          3   
29      30   38          13     119     94104       1   3.30          2   
...    ...  ...         ...     ...       ...     ...    ...        ...   
4970  4971   37          13      95     95821       2   1.70          2   
4971  4972   58          28      73     90024       1   1.40          3   
4972  4973   58          32      41     93401       3   2.20          3   
4973  4974   31           1      68     95045       4   4.00          3   
4974  4975   59          33      64     92867       4   1.70          2   
4975  4976   38          11      29     95207       4   1.00          2   
4976  4977   29           5      31     95039       1   1.80          2   
4977  4978   40          15      54     90266       3   0.80          3   
4978  4979   57          27      63     90210       4   2.00          3   
4979  4980   50          26      92     90740       1   2.60          2   
4980  4981   29           5     135     95762       3   5.30          1   
4981  4982   34           9     195     90266       2   3.00          1   
4982  4983   36          10      45     95126       4   0.20          1   
4983  4984   51          26      72     95370       1   2.90          1   
4984  4985   27           1      98     94043       4   2.30          3   
4985  4986   48          23      30     94720       3   1.70          2   
4986  4987   32           6      78     95825       1   2.90          3   
4987  4988   48          23      43     93943       3   1.70          2   
4988  4989   34           8      85     95134       1   2.50          1   
4989  4990   24           0      38     93555       1   1.00          3   
4990  4991   55          25      58     95023       4   2.00          3   
4991  4992   51          25      

In [3]:
bank_data.describe()

#The max value of mortgage is high, need to normalize before put into machine learning model

ID          Age   Experience       Income      ZIP Code  \
count  5000.000000  5000.000000  5000.000000  5000.000000   5000.000000   
mean   2500.500000    45.338400    20.104600    73.774200  93152.503000   
std    1443.520003    11.463166    11.467954    46.033729   2121.852197   
min       1.000000    23.000000    -3.000000     8.000000   9307.000000   
25%    1250.750000    35.000000    10.000000    39.000000  91911.000000   
50%    2500.500000    45.000000    20.000000    64.000000  93437.000000   
75%    3750.250000    55.000000    30.000000    98.000000  94608.000000   
max    5000.000000    67.000000    43.000000   224.000000  96651.000000   

            Family        CCAvg    Education     Mortgage  Personal Loan  \
count  5000.000000  5000.000000  5000.000000  5000.000000    5000.000000   
mean      2.396400     1.937938     1.881000    56.498800       0.096000   
std       1.147663     1.747659     0.839869   101.713802       0.294621   
min       1.000000     0.000000     1.000000     0.000000       0.000000   
25%       1.000000     0.700000     1.000000     0.000000       0.000000   
50%       2.000000     1.500000     2.000000     0.000000       0.000000   
75%       3.000000     2.500000     3.000000   101.000000       0.000000   
max       4.000000    10.000000     3.000000   635.000000       1.000000   

       Securities Account  CD Account       Online   CreditCard  
count         5000.000000  5000.00000  5000.000000  5000.000000  
mean             0.104400     0.06040     0.596800     0.294000  
std              0.305809     0.23825     0.490589     0.455637  
min              0.000000     0.00000     0.000000     0.000000  
25%              0.000000     0.00000     0.000000     0.000000  
50%              0.000000     0.00000     1.000000     0.000000  
75%              0.000000     0.00000     1.000000     1.000000  
max              1.000000     1.00000     1.000000     1.000000

In [4]:
bank_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
ID                    5000 non-null int64
Age                   5000 non-null int64
Experience            5000 non-null int64
Income                5000 non-null int64
ZIP Code              5000 non-null int64
Family                5000 non-null int64
CCAvg                 5000 non-null float64
Education             5000 non-null int64
Mortgage              5000 non-null int64
Personal Loan         5000 non-null int64
Securities Account    5000 non-null int64
CD Account            5000 non-null int64
Online                5000 non-null int64
CreditCard            5000 non-null int64
dtypes: float64(1), int64(13)
memory usage: 547.0 KB


In [5]:
bank_data.head()

#Need to convert Zip Code into categorical value

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1         0   
1   2   45          19      34     90089       3    1.5          1         0   
2   3   39          15      11     94720       1    1.0          1         0   
3   4   35           9     100     94112       1    2.7          2         0   
4   5   35           8      45     91330       4    1.0          2         0   

   Personal Loan  Securities Account  CD Account  Online  CreditCard  
0              0                   1           0       0           0  
1              0                   1           0       0           0  
2              0                   0           0       0           0  
3              0                   0           0       0           0  
4              0                   0           0       0           1

In [6]:
bank_data.isnull().values.any()

#No Null Value in the dataset

False

In [7]:
#3. Study the target column distribution and state your insights.

#select features
features = bank_data.columns.drop("Personal Loan")
category_features =["ZIP Code","Education","Securities Account", "CD Account", "Online", "CreditCard"]
target = ["Personal Loan"]


#encoding the categorical variable
bank_data_encoded = pd.get_dummies(bank_data[features])
bank_data_encoded["Personal Loan"] = bank_data["Personal Loan"]

# from sklearn.preprocessing import LabelEncoder, OneHotEncoder
# cat_columns_idx = [bank_data.columns.get_loc(col) 
#                    for col in category_features]
# ohe = OneHotEncoder(categorical_features=cat_columns_idx, 
#                     sparse=False, handle_unknown="ignore")
# bank_data_encoded = ohe.fit_transform(bank_data)

bank_data_encoded.head()

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1         0   
1   2   45          19      34     90089       3    1.5          1         0   
2   3   39          15      11     94720       1    1.0          1         0   
3   4   35           9     100     94112       1    2.7          2         0   
4   5   35           8      45     91330       4    1.0          2         0   

   Securities Account  CD Account  Online  CreditCard  Personal Loan  
0                   1           0       0           0              0  
1                   1           0       0           0              0  
2                   0           0       0           0              0  
3                   0           0       0           0              0  
4                   0           0       0           1              0

In [8]:
#Normalize the data
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
features_to_scale = ["Age", "Experience","Income","Family","CCAvg","Mortgage"]
scaled_values = scaler.fit_transform(bank_data_encoded[features_to_scale])
bank_data_encoded["Age"] = scaled_values[:,0]
bank_data_encoded["Experience"] = scaled_values[:,1]
bank_data_encoded["Income"] = scaled_values[:,2]
bank_data_encoded["Family"] = scaled_values[:,3]
bank_data_encoded["CCAvg"] = scaled_values[:,4]
bank_data_encoded["Mortgage"] = scaled_values[:,5]

#4. Split the data into training and test set in the ratio of 70:30 respectively
from sklearn.model_selection import train_test_split
bank_train, bank_test = train_test_split(bank_data_encoded, test_size=0.3)
bank_train.shape, bank_test.shape

((3500, 14), (1500, 14))

In [9]:
bank_data_encoded.head()

ID       Age  Experience    Income  ZIP Code    Family  CCAvg  Education  \
0   1  0.045455    0.086957  0.189815     91107  1.000000   0.16          1   
1   2  0.500000    0.478261  0.120370     90089  0.666667   0.15          1   
2   3  0.363636    0.391304  0.013889     94720  0.000000   0.10          1   
3   4  0.272727    0.260870  0.425926     94112  0.000000   0.27          2   
4   5  0.272727    0.239130  0.171296     91330  1.000000   0.10          2   

   Mortgage  Securities Account  CD Account  Online  CreditCard  Personal Loan  
0       0.0                   1           0       0           0              0  
1       0.0                   1           0       0           0              0  
2       0.0                   0           0       0           0              0  
3       0.0                   0           0       0           0              0  
4       0.0                   0           0       0           1              0

In [13]:
#5. Use different classification models (Logistic, K-NN) to predict the likelihood of a liability
#customer buying personal loans (10 points)

#build the model using Logistic Regression
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(bank_train[features],bank_train[target])



0.8985714285714286


In [20]:
#build the model using KNN
from sklearn.neighbors import KNeighborsClassifier
model1 = KNeighborsClassifier(n_neighbors=2,metric="euclidean")
model1.fit(bank_train[features],bank_train[target])

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
           metric_params=None, n_jobs=None, n_neighbors=2, p=2,
           weights='uniform')

In [30]:
#build the model using random forest
from sklearn.ensemble import RandomForestClassifier
model2 = RandomForestClassifier()
model2.fit(bank_train[features], bank_train[target])

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [31]:
#6. Print the confusion matrix for all the above models (10 points)

#Confusion Matrix
from sklearn.metrics import confusion_matrix

train_predictions_LR = model.predict(bank_train[features])
test_predictions_LR = model.predict(bank_test[features])
train_conf_matrix_LR = confusion_matrix(bank_train[target], train_predictions_LR)
test_conf_matrix_LR = confusion_matrix(bank_test[target],test_predictions_LR)

#evaluate model performance on train and test set
train_accuracy = model.score(bank_train[features],bank_train[target])
test_accuracy = model.score(bank_test[features],bank_test[target])
print(train_accuracy, test_accuracy)

train_predictions_KNN = model1.predict(bank_train[features])
test_predictions_KNN = model1.predict(bank_test[features])
train_conf_matrix_KNN = confusion_matrix(bank_train[target], train_predictions_KNN)
test_conf_matrix_KNN = confusion_matrix(bank_test[target],test_predictions_KNN)


#evaluate model performance on train and test set
train_accuracy = model1.score(bank_train[features],bank_train[target])
test_accuracy = model1.score(bank_test[features],bank_test[target])
print(train_accuracy, test_accuracy)


train_predictions_RF = model2.predict(bank_train[features])
test_predictions_RF = model2.predict(bank_test[features])
train_conf_matrix_RF = confusion_matrix(bank_train[target], train_predictions_RF)
test_conf_matrix_RF = confusion_matrix(bank_test[target],test_predictions_RF)


#evaluate model performance on train and test set
train_accuracy = model2.score(bank_train[features],bank_train[target])
test_accuracy = model2.score(bank_test[features],bank_test[target])
print(train_accuracy, test_accuracy)

0.8985714285714286 0.9166666666666666
0.9094285714285715 0.908
0.9985714285714286 0.9813333333333333


In [24]:
train_conf_matrix_LR

array([[3145,    0],
       [ 355,    0]], dtype=int64)

In [25]:
test_conf_matrix_LR

array([[1375,    0],
       [ 125,    0]], dtype=int64)

In [26]:
train_conf_matrix_KNN

array([[3145,    0],
       [ 317,   38]], dtype=int64)

In [27]:
test_conf_matrix_KNN

array([[1362,   13],
       [ 125,    0]], dtype=int64)

In [32]:
feature_imps = pd.DataFrame(np.array([features,
                                                                             model2.feature_importances_]).T,
                                                           columns=["feature", "importance"])

feature_imps.sort_values(by="importance", ascending=False)

feature  importance
3               Income    0.290794
7            Education    0.219044
6                CCAvg    0.134174
5               Family    0.124537
10          CD Account    0.052788
0                   ID   0.0381875
4             ZIP Code   0.0359733
1                  Age   0.0321092
8             Mortgage   0.0298306
2           Experience   0.0235029
12          CreditCard  0.00819764
11              Online    0.006426
9   Securities Account  0.00443666

In [ ]:
#7. Give your reasoning on which is the best model in this case and state your conclusions (5
#points)

#Random forest got the best result of 99.8% accuracy for training set, and 98.1% accuracy for test set

#The conclusion is that the "Income", "Education", and "CCAvg" are the top 3 factors that can classify if a person purchase the loan or not

#it means that if people have less income, they has higher probability of purchasing the loan