In [5]:
# numpy array creation: np.array()
list = [5, 10, 0, 200]

import numpy as np
arr = np.array(list)

print(arr + 5)

#datatype: type()
print(type(arr[0]))

#check data bytes: nbytes
print(arr.nbytes)

[ 10  15   5 205]
<class 'numpy.int32'>
16


In [11]:
#numpy ndarray creation: np.array(arr, dtype=int)
arr = np.array([2,5,6,8], dtype = int)
print(arr)
print(type(arr))
print(np.result_type(arr))


#np.arange(start, end, step) 
print(np.arange(0,10,1.33, dtype=np.float64))

#np.linspace(start, end, total_count)
print(np.linspace(0,160,5, dtype=np.float64))

[2 5 6 8]
<class 'numpy.ndarray'>
int32
[0.   1.33 2.66 3.99 5.32 6.65 7.98 9.31]
[  0.  40.  80. 120. 160.]


In [16]:
#create matrix 1: np.reshape(row,col)
print(np.array([5,6,8,45,12,52]).reshape(2,3))

#create matrix 2: np.matrix(multi_dimension_array)
print(np.matrix([[1,2],[3,4]]))

#create matrix 3: use mics function:
print(np.eye(3))
print(np.zeros( (4,3) ))
print(np.ones( (3,3), dtype=np.float64))

[[ 5  6  8]
 [45 12 52]]
[[1 2]
 [3 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [30]:
arr1 = np.array([25,56,12,85,34,75],dtype=int)
arr2 = np.array([42,3,86,32,856,46],dtype=int)

#random numpy array
Narr = np.random.rand(6,1)

#change numpy array datatype
arr1 = arr1.astype('complex')

arr1_mat =  arr1.reshape(2,3)
arr2_mat  = arr2.reshape(2,3)

#calculation
result = (arr1_mat*arr1_mat - arr2_mat*arr2_mat) / (arr1_mat - arr2_mat)
print(result)

[[ 67.-0.j  59.+0.j  98.-0.j]
 [117.+0.j 890.-0.j 121.+0.j]]


In [35]:
#Suppose we're given a literacy rate data sample of State X and State Y 
#for two consecutive years measured quarterly on a scale of 0-10. 
#Let us try to arrive at the following outcomes:

S_X = np.array([[2,5,6,5],[4,8,6,5]])
print(S_X)

S_Y = np.array([[6,7,5,9],[7,5,6,4]])
print(S_Y)

#Quarterly difference between each state's literacy rate per year
print(S_Y - S_X)

#Quarters having a literacy rate less than 2.
print(S_X < 2)

twos_mat = np.ones((2,4)) * 2
print(np.less(S_Y, twos_mat))


[[2 5 6 5]
 [4 8 6 5]]
[[6 7 5 9]
 [7 5 6 4]]
[[ 4  2 -1  4]
 [ 3 -3  0 -1]]
[[False False False False]
 [False False False False]]
[[False False False False]
 [False False False False]]


In [43]:
#change value in numpy
four_mat = np.ones((4,4))
count=4
for i in range(3):
    four_mat[i][i]=count
    count=count+1
four_mat

array([[4., 1., 1., 1.],
       [1., 5., 1., 1.],
       [1., 1., 6., 1.],
       [1., 1., 1., 1.]])

In [44]:
#np.arange(number_of_array)
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
#Given a matrix mat and an array arr, 
#for each row of the matrix if elements of Column 1 are equal to 
#the corresponding element of the array, 
# then print the corresponding value of Column 2 of the matrix.

import numpy as np
mat = np.array([['abc','A'],['def','B'],['ghi','C'],['jkl','D']])
arr = np.array(['abc','dfe','ghi','kjl']) 

for x in range(len(mat)):
    for y in range(len(arr)):
        if mat[x,0] == arr[y]:
            print(mat[x,1])

A
C


In [57]:
#np.array[:,sort_by_col].argsort()
import numpy as np
mat = np.array([[1,21,3],[5,4,2],[56,12,4]])

mat[mat[:,1].argsort()]

array([1, 2, 0], dtype=int64)

In [69]:
#find top 4 maximum value
import numpy as np
arr = np.array([90, 14, 24, 13, 13, 590, 0, 45, 16, 50])

sort_arr =  np.sort(arr)[::-1]
for i in range(4):
    print(sort_arr[i])

590
90
50
45


In [71]:
#find nearest value
arr = np.array([10,55,22,3,6,44,9,54])
nearest_to = 50

sort_arr =  np.sort(arr)
n = arr.flat[np.abs(arr - nearest_to).argmin()]
n

54

In [75]:
#Quarters having a literacy rate with cumulative sum of more than or equal to 8 per year.

X_cumsum = np.cumsum(S_X, axis=1)
print(X_cumsum)
print(X_cumsum >=8)


Y_cumsum = np.cumsum(S_Y, axis=1)
print(Y_cumsum)
print(Y_cumsum >=8)

[[2 5 6 5]
 [4 8 6 5]]
[[6 7 5 9]
 [7 5 6 4]]
[[ 2  7 13 18]
 [ 4 12 18 23]]
[[False False  True  True]
 [False  True  True  True]]
[[ 6 13 18 27]
 [ 7 12 18 22]]
[[False  True  True  True]
 [False  True  True  True]]


In [76]:
#Mean of each year's literacy rate of State X and mean of each quarterly's literacy rate of State Y.

print(np.mean(S_X, axis = 1))

[4.5  5.75]


In [82]:
#sort by row/col

import numpy as np

mat = np.array([[10,5,9],
                [2,20,6],
                [8,3,30]]).reshape(3,3)

result = np.amax(mat, axis=0)
result = np.amax(mat, axis=1)
result

array([10, 20, 30])